name: massai mara park 01 docker ec2

on:
  workflow_dispatch

env:
  DOCKER_USERNAME: kangheejun
  IMAGE_NAME: massai_mara
  IMAGE_TAG: v${{ github.run_number }}
  HOSTNAME: 52.91.3.174
  USERNAME: ubuntu

jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: false
          load: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}:arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save Docker image
        run: docker save ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}:arm64 > image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  hub_push:
    name: Push Docker Image to DockerHub
    needs: build_image
    runs-on: ubuntu-22.04

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load < image.tar

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to DockerHub
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker tag ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Logout from DockerHub
        if: always()
        run: docker logout

  upload_compose:
    name: Upload Compose File to EC2
    needs: hub_push
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Compose to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOSTNAME }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.EC2_PRIVATEKEY }}
          port: 22
          source: "./compose-multijobs.yaml"
          target: "/home/${{ env.USERNAME }}"

  run_test:
    name: Run and Test on EC2
    needs: upload_compose
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOSTNAME }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.EC2_PRIVATEKEY }}
          port: 22
          script: |
            docker compose -f ./compose-multijobs.yaml down
            docker image rm -f kangheejun/massai_mara:latest
            docker compose -f ./compose-multijobs.yaml up -d
            sleep 15

            docker compose -f ./compose-multijobs.yaml ps
            docker compose -f ./compose-multijobs.yaml logs